# Generated by Django 5.2.7 on 2025-11-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaDueno',
            fields=[
                ('id_dueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('por_chofer', models.IntegerField(help_text='Porcentaje ganancia chofer')),
                ('por_dueno', models.IntegerField(help_text='Porcentaje ganancia dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='viaje',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('num_resena', models.IntegerField(default=0)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_uber.chofer')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_uber.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='viaje',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='app_uber.pagos'),
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('tipo_tarjeta', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('cv', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='app_uber.usuariopasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_carro', models.CharField(max_length=50)),
                ('modelo_carro', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('tipo_carro', models.CharField(max_length=50)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app_uber.chofer')),
            ],
        ),
    ]
